version: '2'
services:
  web:
    volumes:
      - ./:/webhook_handler
    ports:
      - "8200:80"
    environment:
      - FLASK_APP=webhook_handler.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
